/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_APP_TITLE: process.env.NEXT_PUBLIC_APP_TITLE,
    NEXT_PUBLIC_APP_DESCRIPTION: process.env.NEXT_PUBLIC_APP_DESCRIPTION,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
    NEXT_PUBLIC_CHAIN_NAME: process.env.NEXT_PUBLIC_CHAIN_NAME,
    NEXT_PUBLIC_CHAIN_SYMBOL: process.env.NEXT_PUBLIC_CHAIN_SYMBOL,
    NEXT_PUBLIC_CHAIN_DECIMALS: process.env.NEXT_PUBLIC_CHAIN_DECIMALS,
    NEXT_PUBLIC_CHAIN_UNITS: process.env.NEXT_PUBLIC_CHAIN_UNITS,
    NEXT_PUBLIC_CHAIN_UNIT_NAME: process.env.NEXT_PUBLIC_CHAIN_UNIT_NAME
  }
}

module.exports = nextConfig